### ISSUE TITLE
Too Big & No camera

### ISSUE THREAD

**Issue by Randowlh** [wh201906/Notch#1]
Not upstream enough

**Comment by wh201906** [comment]
The size is now configurable.
IDK how the camera looks like.
You can buy me the newest Macbook Pro so I can be "upstream".
嘤嘤嘤

**Comment by huangxinjian** [comment]
两个中国人搁这说英文嗷，还缩写 IDK 😂😂😂😂😂

**Comment by wh201906** [comment]
![233](https://gist.githubusercontent.com/wh201906/0422f4e11afeb0c1fe1c0cdb76132cd6/raw/80e9877281c545c272be4702098adedf588a4b3c/23333.png)
